apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-1
  namespace: ckad
spec: 
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "sleep"
        - "5"

