apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: dbrt4
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql    
    spec:      
      terminationGracePeriodSeconds: 10      
      securityContext:
        fsGroup: 2000
        runAsGroup: 10009
        runAsUser: 10001     
      containers:
      - name: mssql
        image: nousvptestacr.azurecr.io/sqlserver2019:281401
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql  
        securityContext:
          allowPrivilegeEscalation: false   
      imagePullSecrets:
      - name: nousecretregistryconnection
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
  namespace: dbrt4
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP