apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-pvc
  namespace: pitstop
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "az-disk-invoice"