apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv4
spec:
  capacity:
    storage: 20Gi
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: MyDisk4
    diskURI:  /subscriptions/15c096af-64c9-4097-a760-1f58cbbc62fe/resourceGroups/MC_onesimrg_maltax_southeastasia/providers/Microsoft.Compute/disks/MyDisk4