kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-data-pvc
  namespace: db
  annotations:
    volume.beta.kubernetes.io/storage-class: sc-azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi