apiVersion: apps/v1
kind: Deployment
metadata:   
  name: mssql-deployment-static
  namespace: db2019   
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mssql1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mssql1
    spec:
      containers:
      - env:
        - name: MSSQL_PID
          value: Standard
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: AksSql2020#
        - name: MSSQL_MEMORY_LIMIT_MB
          value: 6000Mi
        image: nousvptestacr.azurecr.io/nousmssql2019:v1
        imagePullPolicy: IfNotPresent
        name: mssql1
        ports:
        - containerPort: 1433
          protocol: TCP
        resources:
          limits:
            cpu: "3"
            memory: 6Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssqldb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      terminationGracePeriodSeconds: 10
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql-data-pvc