kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-pvc-dyn
  namespace: db2019
  annotations:
    volume.beta.kubernetes.io/storage-class: sc-azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi