apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv
  namespace: db
spec:
  capacity:
    storage: 80Gi
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: Kube_static_disk
    diskURI:  /subscriptions/2d3e797c-a450-4a57-8aac-e7ffb72a7570/resourceGroups/MC_BLR_Azure_CoC_C1_maltax_centralus/providers/Microsoft.Compute/disks/Kube_static_disk
              