apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data-pvcx
  namespace: db2020
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi