apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azdevops-apps
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-apps
subjects:
- kind: User
  name: system:serviceaccount:default:azdevops
  apiGroup: rbac.authorization.k8s.io